/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GSys.Client.Client.OpenAPIDateConverter;

namespace GSys.Client.Model
{
    /// <summary>
    /// GetMarketItemResponseOrders
    /// </summary>
    [DataContract(Name = "GetMarketItemResponseOrders")]
    public partial class GetMarketItemResponseOrders : IEquatable<GetMarketItemResponseOrders>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketItemResponseOrders" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMarketItemResponseOrders() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketItemResponseOrders" /> class.
        /// </summary>
        /// <param name="buy">buy (required).</param>
        /// <param name="sell">sell (required).</param>
        public GetMarketItemResponseOrders(List<GetMarketItemResponseOrder> buy = default(List<GetMarketItemResponseOrder>), List<GetMarketItemResponseOrder> sell = default(List<GetMarketItemResponseOrder>))
        {
            // to ensure "buy" is required (not null)
            if (buy == null)
            {
                throw new ArgumentNullException("buy is a required property for GetMarketItemResponseOrders and cannot be null");
            }
            this.Buy = buy;
            // to ensure "sell" is required (not null)
            if (sell == null)
            {
                throw new ArgumentNullException("sell is a required property for GetMarketItemResponseOrders and cannot be null");
            }
            this.Sell = sell;
        }

        /// <summary>
        /// Gets or Sets Buy
        /// </summary>
        [DataMember(Name = "buy", IsRequired = true, EmitDefaultValue = true)]
        public List<GetMarketItemResponseOrder> Buy { get; set; }

        /// <summary>
        /// Gets or Sets Sell
        /// </summary>
        [DataMember(Name = "sell", IsRequired = true, EmitDefaultValue = true)]
        public List<GetMarketItemResponseOrder> Sell { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMarketItemResponseOrders {\n");
            sb.Append("  Buy: ").Append(Buy).Append("\n");
            sb.Append("  Sell: ").Append(Sell).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetMarketItemResponseOrders);
        }

        /// <summary>
        /// Returns true if GetMarketItemResponseOrders instances are equal
        /// </summary>
        /// <param name="input">Instance of GetMarketItemResponseOrders to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetMarketItemResponseOrders input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Buy == input.Buy ||
                    this.Buy != null &&
                    input.Buy != null &&
                    this.Buy.SequenceEqual(input.Buy)
                ) && 
                (
                    this.Sell == input.Sell ||
                    this.Sell != null &&
                    input.Sell != null &&
                    this.Sell.SequenceEqual(input.Sell)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Buy != null)
                {
                    hashCode = (hashCode * 59) + this.Buy.GetHashCode();
                }
                if (this.Sell != null)
                {
                    hashCode = (hashCode * 59) + this.Sell.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
