/*
 * api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GSys.Client.Client.OpenAPIDateConverter;

namespace GSys.Client.Model
{
    /// <summary>
    /// UpdatePlayerStoresResponseStore
    /// </summary>
    [DataContract(Name = "UpdatePlayerStoresResponseStore")]
    public partial class UpdatePlayerStoresResponseStore : IEquatable<UpdatePlayerStoresResponseStore>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePlayerStoresResponseStore" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdatePlayerStoresResponseStore() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePlayerStoresResponseStore" /> class.
        /// </summary>
        /// <param name="blocks">blocks (required).</param>
        /// <param name="revision">revision (required).</param>
        public UpdatePlayerStoresResponseStore(int blocks = default(int), long revision = default(long))
        {
            this.Blocks = blocks;
            this.Revision = revision;
        }

        /// <summary>
        /// Gets or Sets Blocks
        /// </summary>
        [DataMember(Name = "blocks", IsRequired = true, EmitDefaultValue = true)]
        public int Blocks { get; set; }

        /// <summary>
        /// Gets or Sets Revision
        /// </summary>
        [DataMember(Name = "revision", IsRequired = true, EmitDefaultValue = true)]
        public long Revision { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdatePlayerStoresResponseStore {\n");
            sb.Append("  Blocks: ").Append(Blocks).Append("\n");
            sb.Append("  Revision: ").Append(Revision).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdatePlayerStoresResponseStore);
        }

        /// <summary>
        /// Returns true if UpdatePlayerStoresResponseStore instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdatePlayerStoresResponseStore to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdatePlayerStoresResponseStore input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Blocks == input.Blocks ||
                    this.Blocks.Equals(input.Blocks)
                ) && 
                (
                    this.Revision == input.Revision ||
                    this.Revision.Equals(input.Revision)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Blocks.GetHashCode();
                hashCode = (hashCode * 59) + this.Revision.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Blocks (int) minimum
            if (this.Blocks < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Blocks, must be a value greater than or equal to 0.", new [] { "Blocks" });
            }

            // Revision (long) minimum
            if (this.Revision < (long)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Revision, must be a value greater than or equal to 0.", new [] { "Revision" });
            }

            yield break;
        }
    }

}
